global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'nestjs-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
      # - targets: ['my-backend:3000'] # 도커환경으로 킬때 변경할것(서버에서)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'glances'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['glances:9091']
